import * as fs from 'fs';
import * as path from 'path';
import { execFileSync } from 'child_process';
import { ConfigManager } from '../ConfigManager';
import type { LLMClient } from '../LLMClient';
import { Logger } from '../../utils/Logger';
import { resolveExecutionHistoryPath } from '../ReportPaths';
import { generatedSpecPath } from './GeneratedPaths';
import { evaluateCompactCoverageGate, evaluateCompactVerifiedGate, formatCompactCoverageLog, getCompactWorkflow } from './CompactWorkflow';
import { isSuccessfulActHistory } from './HistoryReuse';
import { resolvePlaywrightCli } from '../PlaywrightCliPath';
import { BrowserProviderRegistry } from '../browserProviders/BrowserProviderRegistry';
import { findCliInstallRoot } from '../../cli/ProjectContext';
import { ensureBrowserUsePython, splitPythonCommand } from '../../integrations/browser_use/PythonRuntime';
import type { ReportCodegenInfo } from '../execution_report/types';
import type { CodegenMetadata, CodegenProfilePlan } from './GenerationPlan';
import type { RawExecutionStep } from './ExecutionTrace';

export interface GeneratedFile {
  path: string;
  content?: string;
}

export type CodegenMode = 'openhands';

export interface PostExecutionCodegenResult {
  success: boolean;
  summary: string;
  files: GeneratedFile[];
  metadata?: CodegenMetadata;
  reportCodegen?: ReportCodegenInfo;
}

/** Same keys written by `webpilot init` (`project.language` / tool / pattern). */
export function readProjectCodegenProfile(): CodegenProfilePlan {
  const config = ConfigManager.getInstance();
  const generatedCodePath = String(config.get('framework.generatedCodePath', '') || '')
    .replace(/\\/g, '/')
    .replace(/\/$/, '');
  const configuredLanguage = config.get('project.language') as string | undefined;
  let language = configuredLanguage;
  if (!language && /(?:^|\/)tests\/generated$/.test(generatedCodePath)) {
    language = 'python';
  }
  language = language || 'typescript';
  const automationTool = config.get('project.automationTool', 'playwright');
  const frameworkPattern = config.get('project.frameworkPattern', 'pom');
  const testFramework =
    config.get('project.testFramework') ||
    (language === 'python' ? 'pytest' : 'playwright-test');
  return { language, automationTool, frameworkPattern, testFramework };
}

export function resolveCodegenMode(): CodegenMode {
  return 'openhands';
}

function loadHistoryDocument(
  testName: string,
  provided?: Record<string, unknown>
): Record<string, unknown> | undefined {
  if (provided) return provided;
  const historyPath = resolveExecutionHistoryPath(testName);
  if (!fs.existsSync(historyPath)) return undefined;
  try {
    return JSON.parse(fs.readFileSync(historyPath, 'utf8')) as Record<string, unknown>;
  } catch {
    return undefined;
  }
}

function codegenBlocked(
  summary: string
): PostExecutionCodegenResult {
  return { success: false, summary, files: [] };
}

function buildMetadata(slug: string, files: GeneratedFile[], specPath: string): CodegenMetadata {
  return {
    generatedBy: 'webpilot',
    scenarioSlug: slug,
    sourceTrace: resolveExecutionHistoryPath(slug),
    sourcePlan: '',
    profile: 'typescript/playwright/pom',
    specPath,
    pageObjectPaths: files
      .map((file) => file.path)
      .filter((file) => /\/pages\/.+\.ts$/i.test(file.replace(/\\/g, '/'))),
    generatedFiles: files.map((file) => file.path),
    replayCommand: `webpilot replay ${specPath}`,
    validationCommand: `node ${resolvePlaywrightCli()} test ${specPath} --config=packages/test-framework/playwright.config.ts --project=chromium`,
    updatedAt: new Date().toISOString(),
    mode: 'llm',
  };
}

function buildReportCodegen(metadata: CodegenMetadata, files: GeneratedFile[]): ReportCodegenInfo {
  return {
    mode: 'openhands',
    specPath: metadata.specPath || generatedSpecPath(metadata.scenarioSlug),
    pageObjectPaths: metadata.pageObjectPaths || [],
    metadataPath: '',
    tracePath: '',
    planPath: '',
    replayCommand: metadata.replayCommand || `webpilot replay ${metadata.specPath}`,
    validationCommand: metadata.validationCommand,
    generatedFiles: files.map((file) => file.path),
    notes: ['Generated by OpenHands SDK from WebPilot execution evidence.'],
  };
}

function validateGeneratedSpec(specPath: string): { ok: boolean; detail: string } {
  const headed = BrowserProviderRegistry.resolveHeaded();
  try {
    execFileSync(
      process.execPath,
      [
        resolvePlaywrightCli(),
        'test',
        specPath,
        '--config=packages/test-framework/playwright.config.ts',
        '--project=chromium',
        headed ? '--headed' : '--headless',
      ],
      { cwd: process.cwd(), env: process.env, stdio: 'inherit' }
    );
    return { ok: true, detail: `Playwright validation passed: ${specPath}` };
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : String(error);
    return { ok: false, detail: `Generated code failed validation for ${specPath}: ${message}` };
  }
}

function parseJsonOutput(stdout: string): Record<string, unknown> {
  const raw = (stdout || '').trim();
  if (!raw) return {};
  const lastLine = raw.split(/\r?\n/).filter(Boolean).at(-1) || '{}';
  return JSON.parse(lastLine) as Record<string, unknown>;
}

function runOpenHandsPython(args: string[]): Record<string, unknown> {
  const pythonPath = ensureBrowserUsePython();
  const installRoot = findCliInstallRoot();
  const { exe, prefixArgs } = splitPythonCommand(pythonPath);
  const out = execFileSync(
    exe,
    [...prefixArgs, '-m', 'integrations.openhands_codegen', ...args],
    {
      cwd: process.cwd(),
      env: {
        ...process.env,
        WEBPILOT_PROJECT_ROOT: process.cwd(),
        WEBPILOT_INSTALL_ROOT: installRoot,
        PYTHONPATH: [
          path.join(installRoot, 'packages', 'browser-use'),
          path.join(installRoot, 'src'),
        ].join(path.delimiter),
      },
      encoding: 'utf8',
      stdio: ['pipe', 'pipe', 'pipe'],
    }
  );
  return parseJsonOutput(out);
}

export async function runPostExecutionCodegen(options: {
  testName: string;
  testFilePath: string;
  executionHistory: RawExecutionStep[];
  llmClient: LLMClient;
  architecture: 'flat' | 'pom' | 'bdd' | 'pom-bdd';
  symbolGraphContext?: string;
  fallbackReason?: string;
  validate?: boolean;
  historyDocument?: Record<string, unknown>;
  skipActHistoryHeal?: boolean;
}): Promise<PostExecutionCodegenResult> {
  void options.executionHistory;
  void options.llmClient;
  void options.architecture;
  void options.symbolGraphContext;
  void options.fallbackReason;
  void options.skipActHistoryHeal;

  const historyDocument = loadHistoryDocument(options.testName, options.historyDocument);
  if (!historyDocument || !isSuccessfulActHistory(historyDocument)) {
    Logger.warn('Skipping codegen — only successful executions generate code');
    return codegenBlocked(
      'Codegen skipped — execution was not successful. Fix the failing run (or use --force-discovery) before generating code.'
    );
  }

  const compact = getCompactWorkflow(historyDocument);
  if (compact) {
    const coverageLog = formatCompactCoverageLog(compact);
    if (coverageLog) Logger.detail(coverageLog);
    const coverageGate = evaluateCompactCoverageGate(compact, { codegen: true });
    if (!coverageGate.ok) {
      Logger.warn(coverageGate.message);
      return codegenBlocked(
        'Codegen blocked — compact workflow NL coverage incomplete. ' + coverageGate.message
      );
    }
    const verifiedGate = evaluateCompactVerifiedGate(compact);
    if (!verifiedGate.ok) {
      Logger.warn(verifiedGate.message);
      return codegenBlocked(`Codegen blocked — ${verifiedGate.message}`);
    }
  }

  const projectProfile = readProjectCodegenProfile();
  if (!(projectProfile.language === 'typescript' && projectProfile.automationTool === 'playwright')) {
    return codegenBlocked(
      `OpenHands codegen currently supports only typescript/playwright. Current profile is ${projectProfile.language}/${projectProfile.automationTool}.`
    );
  }

  const specPath = generatedSpecPath(options.testName, process.cwd());
  const historyPath = resolveExecutionHistoryPath(options.testName);
  Logger.info('Codegen mode: openhands (WebPilot discovery → OpenHands spec generation)');

  let payload: Record<string, unknown>;
  try {
    payload = runOpenHandsPython([
      String(historyPath),
      options.testName,
      '--workspace',
      process.cwd(),
      '--spec-path',
      specPath,
      '--validate',
      options.validate === false ? '0' : '1',
    ]);
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : String(error);
    Logger.error(`OpenHands codegen failed: ${message}`);
    return codegenBlocked(`OpenHands codegen failed: ${message}`);
  }

  if (payload.success !== true) {
    const message = String(payload.summary || payload.error || 'OpenHands codegen failed');
    Logger.error(message);
    return codegenBlocked(message);
  }

  const files = Array.isArray(payload.filesChanged)
    ? (payload.filesChanged as Array<Record<string, unknown>>).map((item) => ({
        path: String(item.path || ''),
        content: typeof item.content === 'string' ? item.content : undefined,
      }))
    : [];
  const metadata = buildMetadata(options.testName, files, specPath);
  const validation =
    options.validate === false ? { ok: true, detail: 'Validation skipped by --no-validate' } : validateGeneratedSpec(specPath);
  if (!validation.ok) {
    return {
      success: false,
      summary: validation.detail,
      files,
      metadata,
      reportCodegen: buildReportCodegen(metadata, files),
    };
  }

  const summary = String(
    payload.summary ||
      `Codegen (openhands) wrote ${files.length} file(s) for ${options.testName}. Replay with: webpilot replay ${specPath}`
  );
  Logger.success(summary);
  return {
    success: true,
    summary,
    files,
    metadata,
    reportCodegen: buildReportCodegen(metadata, files),
  };
}
