import React from 'react';
import { createRoot } from 'react-dom/client';
import { App } from './App';
import { Report } from './types';
import './styles/report.css';

const demo: Report = {
  generatedAt: new Date().toISOString(), suiteName: 'Commerce regression',
  environment: {name:'Staging', baseUrl:'https://staging.example.com'},
  browser: {target:'chromium', channel:'Chrome', headless:true, viewport:{width:1440,height:900}, video:'retain-on-failure', trace:'on', screenshots:'only-on-failure'},
  framework: {name:'Playwright',version:'1.60.0',useBrowserUse:true,activeProvider:'local'},
  overview: {total:2,executed:2,passed:1,failed:1,skipped:0,cancelled:0,passRate:50,totalSteps:17,totalCostUsd:.021,totalTokens:6820,totalDurationMs:94200,retryRate:25,generatedTests:2,estimatedHoursSaved:1.6},
  historyOverview: {totalRuns:6,promptTokens:17600,completionTokens:4300,totalTokens:21900,totalCostUsd:.074,llmCalls:22},
  suiteAiAnalysis:'## Shared diagnosis\nThe checkout failure follows a selector refactor. The locator was repaired, but the confirmation response remained delayed.\n\n- Validate `POST /orders` latency.\n- Promote the learned role locator.',
  testCases: [
    {slug:'booking-search',testName:'Booking search returns available hotels',status:'PASSED',timestamp:new Date().toISOString(),stepsExecuted:8,durationMs:38200,nlSteps:['Open search','Choose dates','Verify results'],executionSteps:[],urlSequence:['https://staging.example.com/search'],runtimeInsights:[],codegenSummary:'Generated and validated',artifacts:{screenshots:[]},pricing:{promptTokens:2100,completionTokens:740,totalTokens:2840,estimatedCostUsd:.008,llmCalls:3,model:'gpt-4.1'},runHistory:[{runId:'run-1',timestamp:new Date(Date.now()-172800000).toISOString(),status:'FAILED',stepsExecuted:7,retries:0,pricing:{promptTokens:1800,completionTokens:600,totalTokens:2400,estimatedCostUsd:.007,llmCalls:3}},{runId:'run-2',timestamp:new Date(Date.now()-86400000).toISOString(),status:'PASSED',stepsExecuted:8,retries:1,pricing:{promptTokens:2000,completionTokens:690,totalTokens:2690,estimatedCostUsd:.008,llmCalls:3}},{runId:'run-3',timestamp:new Date().toISOString(),status:'PASSED',stepsExecuted:8,retries:0,pricing:{promptTokens:2100,completionTokens:740,totalTokens:2840,estimatedCostUsd:.008,llmCalls:3}}],risk:{score:24,level:'low',factors:[{id:'unverified-locators',weight:9,detail:'Three locators lack inventory verification.'}]},completeness:{grade:'B',score:84,missing:[],warnings:['3 unverified locators']},healingCount:0,codegenQuality:'good',evidenceLocators:{total:7,verified:4,unverified:3,verifiedRatio:.57},evidenceTimeline:[{index:1,action:'navigate',nlStep:'Open hotel search',url:'https://staging.example.com/search',healed:false,outcome:'passed'},{index:2,action:'assert',nlStep:'Verify hotel results',healed:false,outcome:'passed',locator:{kind:'role',value:'list',verified:true,verifiedBy:'inventory',matchCount:1},assertion:{kind:'visible'}}],evidenceHealing:[],evidenceDrift:[],rootCauseAnalysis:{status:'not-required',summary:'No failure required analysis.',findings:[]},aiAnalysis:'The search completed successfully with verified result-list evidence.'},
    {slug:'guest-checkout',testName:'Guest checkout places an order',status:'FAILED',timestamp:new Date().toISOString(),stepsExecuted:9,durationMs:56000,nlSteps:['Add item','Checkout','Confirm order'],executionSteps:[],urlSequence:['https://staging.example.com/checkout'],runtimeInsights:[{type:'error',message:'Confirmation state timed out.'}],codegenSummary:'Generated with repair',artifacts:{screenshots:['artifacts/checkout-timeout.png'],trace:'artifacts/trace.zip'},pricing:{promptTokens:2900,completionTokens:1080,totalTokens:3980,estimatedCostUsd:.013,llmCalls:5,model:'gpt-4.1'},runHistory:[{runId:'run-1',timestamp:new Date(Date.now()-172800000).toISOString(),status:'PASSED',stepsExecuted:8,retries:0,pricing:{promptTokens:2400,completionTokens:800,totalTokens:3200,estimatedCostUsd:.01,llmCalls:4}},{runId:'run-2',timestamp:new Date(Date.now()-86400000).toISOString(),status:'FAILED',stepsExecuted:9,retries:1,pricing:{promptTokens:2800,completionTokens:1000,totalTokens:3800,estimatedCostUsd:.012,llmCalls:5}},{runId:'run-3',timestamp:new Date().toISOString(),status:'FAILED',stepsExecuted:9,retries:0,pricing:{promptTokens:2900,completionTokens:1080,totalTokens:3980,estimatedCostUsd:.013,llmCalls:5}}],risk:{score:72,level:'high',factors:[{id:'assertion-failed',weight:40,detail:'Final order assertion failed.'},{id:'page-drift',weight:22,detail:'Checkout fingerprint changed.'}]},completeness:{grade:'C',score:68,missing:['confirmation screenshot'],warnings:['4 unverified locators']},healingCount:1,codegenQuality:'degraded',evidenceRef:'runtime/reports/evidence/guest-checkout.json',evidenceLocators:{total:9,verified:5,unverified:4,verifiedRatio:.56},evidenceTimeline:[{index:8,action:'click',nlStep:'Place order',healed:true,outcome:'passed',locator:{kind:'role',value:"button 'Place order'",verified:true,verifiedBy:'accessibility',matchCount:1}},{index:9,action:'assert',nlStep:'Confirm order',healed:false,outcome:'failed',error:'Confirmation state did not appear before timeout.'}],evidenceHealing:[{stepIndex:8,brokenSelector:'#btn-old',healedSelector:"getByRole('button', { name: 'Place order' })",confidence:.82,classification:'refactor',committed:true}],evidenceDrift:[{pageKey:'checkout',previousFingerprint:'sha256:2f04…b891',currentFingerprint:'sha256:7ac1…90e3',added:8,removed:3,changed:4}],rootCauseAnalysis:{status:'grounded',summary:'The checkout submitted after a selector repair, but no confirmation state was observed.',findings:[{claim:'The primary button changed during a checkout refactor.',confidence:.91,citedEventIds:['evt-123','evt-124']},{claim:'The order service may have delayed confirmation.',confidence:.44,citedEventIds:[]}],missingEvidence:['Response body for POST /orders']},aiAnalysis:'## Diagnosis\nThe selector refactor was repaired. The remaining timeout points to delayed order confirmation rather than an interaction failure.'}
  ]
};
function readReport(): Report {
  const raw = document.getElementById('webpilot-report-data')?.textContent?.trim();
  if (raw?.startsWith('{')) { try { const parsed=JSON.parse(raw); if(parsed?.suiteName) return parsed; } catch {/* demo */} }
  return demo;
}
const report=readReport();
document.title=`${report.suiteName} — WebPilot`;
createRoot(document.getElementById('root')!).render(<React.StrictMode><App report={report}/></React.StrictMode>);
