import { GeneratedFile } from '../../../agents/CodegenAgent';
import { ExecutionTrace, TraceStep } from '../ExecutionTrace';
import { CodegenProfilePlan, GenerationPlan, PlannedFile } from '../GenerationPlan';
import { AssertionEmitter } from '../../assertions/AssertionEmitter';
import {
  camelCase,
  CodegenProfile,
  escapeDouble,
  firstUrl,
  roleParts,
  slugToTitle,
} from './CodegenProfile';

function pageForStep(step: TraceStep, plan: GenerationPlan): PlannedFile | undefined {
  return plan.pageObjects.find((page) => {
    if (!step.url || !page.urlPattern) return false;
    try {
      return new RegExp(page.urlPattern).test(step.url);
    } catch {
      return step.url.includes(page.urlPattern);
    }
  });
}

function ariaRole(role: string): string {
  if (!role) return 'Body';
  return role.charAt(0).toUpperCase() + role.slice(1);
}

function playwrightLocator(step: TraceStep, receiver = 'Page'): string | null {
  const selector = step.selector;
  if (!selector) return null;
  const role = roleParts(selector);
  if (role) {
    return role.name
      ? `${receiver}.GetByRole(AriaRole.${ariaRole(role.role)}, new() { Name = "${escapeDouble(role.name)}" })`
      : `${receiver}.GetByRole(AriaRole.${ariaRole(role.role)})`;
  }
  switch (selector.kind) {
    case 'label':
      return `${receiver}.GetByLabel("${escapeDouble(selector.value)}")`;
    case 'placeholder':
      return `${receiver}.GetByPlaceholder("${escapeDouble(selector.value)}")`;
    case 'testid':
      return `${receiver}.GetByTestId("${escapeDouble(selector.value)}")`;
    case 'text':
      return `${receiver}.GetByText("${escapeDouble(selector.value)}")`;
    default:
      return `${receiver}.Locator("${escapeDouble(selector.value)}")`;
  }
}

function methodName(step: TraceStep): string {
  if (step.action === 'navigate') return 'GoToAsync';
  const base = slugToTitle(step.intent || `${step.action}-${step.index}`);
  if (step.action === 'click' && !base.startsWith('Click')) return `Click${base}Async`;
  if (step.action === 'fill' && !base.startsWith('Fill')) return `Fill${base}Async`;
  if (step.action === 'assert' && !base.startsWith('Assert')) return `Assert${base}Async`;
  return `${base}Async`;
}

function csharpPlaywrightStepLines(step: TraceStep, receiver = 'Page'): string[] {
  const locator = playwrightLocator(step, receiver);
  const assertionLines = (step.assertions || []).flatMap((assertion) =>
    AssertionEmitter.csharpPlaywright(assertion, receiver)
  );
  switch (step.action) {
    case 'navigate':
      return step.url
        ? [`await ${receiver}.GotoAsync("${escapeDouble(step.url)}");`, ...assertionLines]
        : assertionLines;
    case 'click':
      return locator
        ? [`await ${locator}.ClickAsync();`, ...assertionLines]
        : [`// click: ${step.intent}`, ...assertionLines];
    case 'fill':
      return locator
        ? [`await ${locator}.FillAsync("${escapeDouble(step.value || '')}");`, ...assertionLines]
        : [`// fill: ${step.intent}`, ...assertionLines];
    case 'select':
      return locator
        ? [`await ${locator}.SelectOptionAsync("${escapeDouble(step.value || '')}");`, ...assertionLines]
        : [`// select: ${step.intent}`, ...assertionLines];
    case 'assert':
      return assertionLines.length > 0
        ? assertionLines
        : locator
          ? [`await Expect(${locator}).ToBeVisibleAsync();`]
          : [`// assert: ${step.intent}`];
    case 'wait':
      return [`await ${receiver}.WaitForLoadStateAsync(LoadState.NetworkIdle);`];
    default:
      return [`// ${step.action}: ${step.intent}`];
  }
}

function pageObjectContent(page: PlannedFile, steps: TraceStep[], trace: ExecutionTrace): string {
  const className = page.className || 'GeneratedPage';
  const methods = steps
    .map((step) => {
      const lines = csharpPlaywrightStepLines(step).map((line) => `        ${line}`);
      return `    public async Task ${methodName(step)}()\n    {\n${lines.join('\n')}\n    }`;
    })
    .join('\n\n');
  return `using Microsoft.Playwright;

namespace WebPilot.Playwright.Tests.Generated.Pages;

/// <summary>Generated by WebPilot. urlPattern: ${page.urlPattern || firstUrl(trace) || ''}</summary>
public class ${className} : BasePage
{
    public ${className}(IPage page) : base(page)
    {
    }

${methods || '    // No generated actions yet.'}
}
`;
}

function pathBasenameWithoutExt(specPath: string): string {
  const base = specPath.split(/[/\\]/).pop() || specPath;
  return base.replace(/\.cs$/i, '');
}

export class CsharpPlaywrightProfile implements CodegenProfile {
  public readonly id = 'csharp-playwright-pom';
  public readonly language = 'csharp';
  public readonly automationTool = 'playwright';
  public readonly testFramework = 'nunit';
  public readonly patterns = ['pom', 'simple'];

  public matches(profile: CodegenProfilePlan): boolean {
    return profile.language === 'csharp' && profile.automationTool === 'playwright';
  }

  public specPath(slug: string, _profile: CodegenProfilePlan): string {
    return `tests/WebPilot.Playwright.Tests/Generated/${slugToTitle(slug)}Tests.cs`;
  }

  public pagePath(className: string, _profile: CodegenProfilePlan, _url?: string): string {
    return `tests/WebPilot.Playwright.Tests/Generated/Pages/${className}.cs`;
  }

  public replayCommand(specPath: string): string {
    return `dotnet test tests/WebPilot.Playwright.Tests/WebPilot.Playwright.Tests.csproj --filter FullyQualifiedName~${pathBasenameWithoutExt(specPath)}`;
  }

  public emit(trace: ExecutionTrace, plan: GenerationPlan): GeneratedFile[] {
    const files: GeneratedFile[] = [];
    const pageMethods = new Map<number, { className: string; variable: string; method: string }>();

    for (const page of plan.pageObjects) {
      const steps = trace.steps.filter((step) => pageForStep(step, { ...plan, pageObjects: [page] }));
      if (steps.length === 0) continue;
      files.push({ path: page.path, content: pageObjectContent(page, steps, trace) });
      for (const step of steps) {
        if (!page.className) continue;
        pageMethods.set(step.index, {
          className: page.className,
          variable: camelCase(page.className),
          method: methodName(step),
        });
      }
    }

    const imports = new Set<string>([
      'using Microsoft.Playwright;',
      'using Microsoft.Playwright.NUnit;',
      'using WebPilot.Playwright.Tests.Generated.Pages;',
    ]);

    const body: string[] = [];
    const instantiated = new Set<string>();
    for (const step of trace.steps) {
      const mapped = pageMethods.get(step.index);
      if (mapped) {
        if (!instantiated.has(mapped.variable)) {
          body.push(`        var ${mapped.variable} = new ${mapped.className}(Page);`);
          instantiated.add(mapped.variable);
        }
        body.push(`        await ${mapped.variable}.${mapped.method}();`);
      } else {
        body.push(...csharpPlaywrightStepLines(step).map((line) => `        ${line}`));
      }
    }

    const className = `${slugToTitle(trace.scenarioSlug)}Tests`;
    files.push({
      path: plan.specPath,
      content: `${[...imports].sort().join('\n')}

namespace WebPilot.Playwright.Tests.Generated;

[Parallelizable(ParallelScope.Self)]
public class ${className} : PageTest
{
    [Test]
    public async Task ${slugToTitle(trace.scenarioSlug)}()
    {
${body.join('\n')}
    }
}
`,
    });
    return files;
  }

  public validationCommand(_profile: CodegenProfilePlan): string {
    return 'dotnet build tests/WebPilot.Playwright.Tests/WebPilot.Playwright.Tests.csproj';
  }
}
