import { GeneratedFile } from '../../../agents/CodegenAgent';
import { ExecutionTrace, TraceStep } from '../ExecutionTrace';
import { CodegenProfilePlan, GenerationPlan, PlannedFile } from '../GenerationPlan';
import { AssertionEmitter } from '../../assertions/AssertionEmitter';
import {
  camelCase,
  CodegenProfile,
  escapeDouble,
  firstUrl,
  roleParts,
  slugToTitle,
} from './CodegenProfile';

function pageForStep(step: TraceStep, plan: GenerationPlan): PlannedFile | undefined {
  return plan.pageObjects.find((page) => {
    if (!step.url || !page.urlPattern) return false;
    try {
      return new RegExp(page.urlPattern).test(step.url);
    } catch {
      return step.url.includes(page.urlPattern);
    }
  });
}

function byExpression(step: TraceStep): string {
  const selector = step.selector;
  if (!selector) return 'By.CssSelector("body")';
  const role = roleParts(selector);
  if (role?.name) {
    return `By.XPath("//*[@role='${escapeDouble(role.role)}' and normalize-space(.)='${escapeDouble(role.name)}']")`;
  }
  switch (selector.kind) {
    case 'label':
    case 'placeholder':
      return `By.CssSelector("[placeholder='${escapeDouble(selector.value)}']")`;
    case 'testid':
      return `By.CssSelector("[data-testid='${escapeDouble(selector.value)}']")`;
    case 'text':
      return `By.XPath("//*[normalize-space(.)='${escapeDouble(selector.value)}']")`;
    case 'xpath':
      return `By.XPath("${escapeDouble(selector.value)}")`;
    default:
      return `By.CssSelector("${escapeDouble(selector.value)}")`;
  }
}

function methodName(step: TraceStep): string {
  if (step.action === 'navigate') return 'GoTo';
  const base = slugToTitle(step.intent || `${step.action}-${step.index}`);
  if (step.action === 'click' && !base.startsWith('Click')) return `Click${base}`;
  if (step.action === 'fill' && !base.startsWith('Fill')) return `Fill${base}`;
  if (step.action === 'assert' && !base.startsWith('Assert')) return `Assert${base}`;
  return base || `${slugToTitle(step.action)}Step${step.index}`;
}

function csharpStepLines(step: TraceStep, driver = 'Driver'): string[] {
  const assertionLines = (step.assertions || []).flatMap((assertion) =>
    AssertionEmitter.csharpSelenium(assertion, driver)
  );
  switch (step.action) {
    case 'navigate':
      return step.url ? [`Driver.Navigate().GoToUrl("${escapeDouble(step.url)}");`, ...assertionLines] : assertionLines;
    case 'click':
      return [`Driver.FindElement(${byExpression(step)}).Click();`, ...assertionLines];
    case 'fill':
      return [
        `var field = Driver.FindElement(${byExpression(step)});`,
        `field.Clear();`,
        `field.SendKeys("${escapeDouble(step.value || '')}");`,
        ...assertionLines,
      ];
    case 'assert':
      return assertionLines.length > 0
        ? assertionLines
        : [`Assert.That(Driver.FindElement(${byExpression(step)}).Displayed, Is.True);`];
    case 'wait':
      return [`Thread.Sleep(1000);`];
    default:
      return [`// ${step.action}: ${step.intent}`];
  }
}

function pageObjectContent(page: PlannedFile, steps: TraceStep[], trace: ExecutionTrace): string {
  const className = page.className || 'GeneratedPage';
  const methods = steps
    .map((step) => {
      const lines = csharpStepLines(step).map((line) => `        ${line}`);
      return `    public void ${methodName(step)}()\n    {\n${lines.join('\n')}\n    }`;
    })
    .join('\n\n');
  return `using OpenQA.Selenium;

namespace WebPilot.Tests.Generated.Pages;

/// <summary>Generated by WebPilot. urlPattern: ${page.urlPattern || firstUrl(trace) || ''}</summary>
public class ${className} : BasePage
{
    public ${className}(IWebDriver driver) : base(driver)
    {
    }

${methods || '    // No generated actions yet.'}
}
`;
}

function pathBasenameWithoutExt(specPath: string): string {
  const base = specPath.split(/[/\\]/).pop() || specPath;
  return base.replace(/\.cs$/i, '');
}

export class CsharpSeleniumProfile implements CodegenProfile {
  public readonly id = 'csharp-selenium-pom';
  public readonly language = 'csharp';
  public readonly automationTool = 'selenium';
  public readonly testFramework = 'nunit';
  public readonly patterns = ['pom', 'simple'];

  public matches(profile: CodegenProfilePlan): boolean {
    return profile.language === 'csharp' && profile.automationTool === 'selenium';
  }

  public specPath(slug: string, _profile: CodegenProfilePlan): string {
    return `tests/WebPilot.Tests/Generated/${slugToTitle(slug)}Tests.cs`;
  }

  public pagePath(className: string, _profile: CodegenProfilePlan, _url?: string): string {
    return `tests/WebPilot.Tests/Generated/Pages/${className}.cs`;
  }

  public replayCommand(specPath: string): string {
    return `dotnet test tests/WebPilot.Tests/WebPilot.Tests.csproj --filter FullyQualifiedName~${pathBasenameWithoutExt(specPath)}`;
  }

  public emit(trace: ExecutionTrace, plan: GenerationPlan): GeneratedFile[] {
    const files: GeneratedFile[] = [];
    const pageMethods = new Map<number, { className: string; variable: string; method: string }>();

    for (const page of plan.pageObjects) {
      const steps = trace.steps.filter((step) => pageForStep(step, { ...plan, pageObjects: [page] }));
      if (steps.length === 0) continue;
      files.push({ path: page.path, content: pageObjectContent(page, steps, trace) });
      for (const step of steps) {
        if (!page.className) continue;
        pageMethods.set(step.index, {
          className: page.className,
          variable: camelCase(page.className),
          method: methodName(step),
        });
      }
    }

    const imports = new Set<string>([
      'using NUnit.Framework;',
      'using OpenQA.Selenium;',
      'using System.Threading;',
      'using WebPilot.Tests.Support;',
    ]);
    for (const page of plan.pageObjects) {
      if (page.className) {
        imports.add(`using WebPilot.Tests.Generated.Pages;`);
      }
    }

    const body: string[] = [];
    const instantiated = new Set<string>();
    for (const step of trace.steps) {
      const mapped = pageMethods.get(step.index);
      if (mapped) {
        if (!instantiated.has(mapped.variable)) {
          body.push(`        var ${mapped.variable} = new ${mapped.className}(Driver);`);
          instantiated.add(mapped.variable);
        }
        body.push(`        ${mapped.variable}.${mapped.method}();`);
      } else {
        body.push(...csharpStepLines(step).map((line) => `        ${line}`));
      }
    }

    const className = `${slugToTitle(trace.scenarioSlug)}Tests`;
    files.push({
      path: plan.specPath,
      content: `${[...imports].sort().join('\n')}

namespace WebPilot.Tests.Generated;

public class ${className} : BaseTest
{
    [Test]
    public void ${slugToTitle(trace.scenarioSlug)}()
    {
${body.join('\n')}
    }
}
`,
    });
    return files;
  }

  public validationCommand(_profile: CodegenProfilePlan): string {
    return 'dotnet build tests/WebPilot.Tests/WebPilot.Tests.csproj';
  }
}
