import { GeneratedFile } from '../../../agents/CodegenAgent';
import { ExecutionTrace, TraceStep } from '../ExecutionTrace';
import { CodegenProfilePlan, GenerationPlan, PlannedFile } from '../GenerationPlan';
import { AssertionEmitter } from '../../assertions/AssertionEmitter';
import {
  camelCase,
  CodegenProfile,
  escapeDouble,
  firstUrl,
  javaPackageFromPath,
  roleParts,
  slugToTitle,
} from './CodegenProfile';

function pageForStep(step: TraceStep, plan: GenerationPlan): PlannedFile | undefined {
  return plan.pageObjects.find((page) => {
    if (!step.url || !page.urlPattern) return false;
    try {
      return new RegExp(page.urlPattern).test(step.url);
    } catch {
      return step.url.includes(page.urlPattern);
    }
  });
}

function byExpression(step: TraceStep): string {
  const selector = step.selector;
  if (!selector) return 'By.cssSelector("body")';
  const role = roleParts(selector);
  if (role?.name) {
    return `By.xpath("//*[@role='${escapeDouble(role.role)}' and normalize-space(.)='${escapeDouble(role.name)}']")`;
  }
  switch (selector.kind) {
    case 'label':
    case 'placeholder':
      return `By.cssSelector("[placeholder='${escapeDouble(selector.value)}']")`;
    case 'testid':
      return `By.cssSelector("[data-testid='${escapeDouble(selector.value)}']")`;
    case 'text':
      return `By.xpath("//*[normalize-space(.)='${escapeDouble(selector.value)}']")`;
    case 'xpath':
      return `By.xpath("${escapeDouble(selector.value)}")`;
    default:
      return `By.cssSelector("${escapeDouble(selector.value)}")`;
  }
}

function methodName(step: TraceStep): string {
  if (step.action === 'navigate') return 'goTo';
  const base = slugToTitle(step.intent || `${step.action}-${step.index}`);
  const name = base.charAt(0).toLowerCase() + base.slice(1);
  if (step.action === 'click' && !name.startsWith('click')) return `click${base}`;
  if (step.action === 'fill' && !name.startsWith('fill')) return `fill${base}`;
  if (step.action === 'assert' && !name.startsWith('assert')) return `assert${base}`;
  return name || `${step.action}Step${step.index}`;
}

function javaStepLines(step: TraceStep, driver = 'driver'): string[] {
  const assertionLines = (step.assertions || []).flatMap((assertion) =>
    AssertionEmitter.javaSelenium(assertion, driver)
  );
  switch (step.action) {
    case 'navigate':
      return step.url ? [`${driver}.get("${escapeDouble(step.url)}");`, ...assertionLines] : assertionLines;
    case 'click':
      return [`${driver}.findElement(${byExpression(step)}).click();`, ...assertionLines];
    case 'fill':
      return [
        `${driver}.findElement(${byExpression(step)}).clear();`,
        `${driver}.findElement(${byExpression(step)}).sendKeys("${escapeDouble(step.value || '')}");`,
        ...assertionLines,
      ];
    case 'assert':
      return assertionLines.length > 0
        ? assertionLines
        : [`assertTrue(${driver}.findElement(${byExpression(step)}).isDisplayed());`];
    case 'wait':
      return [`new WebDriverWait(${driver}, Duration.ofSeconds(10)).until(webDriver -> true);`];
    default:
      return [`// ${step.action}: ${step.intent}`];
  }
}

function pageObjectContent(page: PlannedFile, steps: TraceStep[], trace: ExecutionTrace): string {
  const className = page.className || 'GeneratedPage';
  const packageName = javaPackageFromPath(page.path);
  const methods = steps
    .map((step) => {
      const lines = javaStepLines(step, 'driver').map((line) => `    ${line}`);
      return `  public void ${methodName(step)}() {\n${lines.join('\n')}\n  }`;
    })
    .join('\n\n');
  return `package ${packageName};\n\nimport static org.junit.jupiter.api.Assertions.assertTrue;\n\nimport java.time.Duration;\nimport org.openqa.selenium.By;\nimport org.openqa.selenium.WebDriver;\nimport org.openqa.selenium.support.ui.WebDriverWait;\n\n/**\n * Generated by WebPilot.\n * urlPattern: ${page.urlPattern || firstUrl(trace) || ''}\n */\npublic class ${className} {\n  private final WebDriver driver;\n\n  public ${className}(WebDriver driver) {\n    this.driver = driver;\n  }\n\n${methods || '  // No generated actions yet.'}\n}\n`;
}

export class JavaSeleniumProfile implements CodegenProfile {
  public readonly id = 'java-selenium-pom';
  public readonly language = 'java';
  public readonly automationTool = 'selenium';
  public readonly testFramework = 'junit';
  public readonly patterns = ['pom', 'simple'];

  public matches(profile: CodegenProfilePlan): boolean {
    return profile.language === 'java' && profile.automationTool === 'selenium';
  }

  public specPath(slug: string): string {
    return `src/test/java/webpilot/generated/${slugToTitle(slug)}Test.java`;
  }

  public pagePath(className: string): string {
    return `src/test/java/webpilot/generated/pages/${className}.java`;
  }

  public replayCommand(): string {
    return 'mvn test';
  }

  public emit(trace: ExecutionTrace, plan: GenerationPlan): GeneratedFile[] {
    const files: GeneratedFile[] = [];
    const pageMethods = new Map<number, { className: string; variable: string; method: string }>();
    for (const page of plan.pageObjects) {
      const steps = trace.steps.filter((step) => pageForStep(step, { ...plan, pageObjects: [page] }));
      if (steps.length === 0) continue;
      files.push({ path: page.path, content: pageObjectContent(page, steps, trace) });
      for (const step of steps) {
        if (!page.className) continue;
        pageMethods.set(step.index, {
          className: page.className,
          variable: camelCase(page.className),
          method: methodName(step),
        });
      }
    }

    const testPackage = javaPackageFromPath(plan.specPath);
    const imports = new Set<string>([
      'import static org.junit.jupiter.api.Assertions.assertTrue;',
      'import org.junit.jupiter.api.AfterEach;',
      'import org.junit.jupiter.api.BeforeEach;',
      'import org.junit.jupiter.api.Test;',
      'import org.openqa.selenium.WebDriver;',
      'import org.openqa.selenium.chrome.ChromeDriver;',
    ]);
    for (const page of plan.pageObjects) {
      if (page.className) imports.add(`import webpilot.generated.pages.${page.className};`);
    }

    const body: string[] = [];
    const instantiated = new Set<string>();
    for (const step of trace.steps) {
      const mapped = pageMethods.get(step.index);
      if (mapped) {
        if (!instantiated.has(mapped.variable)) {
          body.push(`    ${mapped.className} ${mapped.variable} = new ${mapped.className}(driver);`);
          instantiated.add(mapped.variable);
        }
        body.push(`    ${mapped.variable}.${mapped.method}();`);
      } else {
        body.push(...javaStepLines(step, 'driver').map((line) => `    ${line}`));
      }
    }

    const className = `${slugToTitle(trace.scenarioSlug)}Test`;
    files.push({
      path: plan.specPath,
      content: `package ${testPackage};\n\n${[...imports].sort().join('\n')}\n\npublic class ${className} {\n  private WebDriver driver;\n\n  @BeforeEach\n  public void setUp() {\n    driver = new ChromeDriver();\n  }\n\n  @AfterEach\n  public void tearDown() {\n    if (driver != null) {\n      driver.quit();\n    }\n  }\n\n  @Test\n  public void ${camelCase(trace.scenarioSlug)}() {\n${body.join('\n')}\n  }\n}\n`,
    });
    return files;
  }

  public validationCommand(): string {
    return 'mvn test';
  }
}
