import { GeneratedFile } from '../../../agents/CodegenAgent';
import { ExecutionTrace, TraceStep } from '../ExecutionTrace';
import { CodegenProfilePlan, GenerationPlan, PlannedFile } from '../GenerationPlan';
import { AssertionEmitter } from '../../assertions/AssertionEmitter';
import {
  camelCase,
  CodegenProfile,
  escapeDouble,
  firstUrl,
  roleParts,
  snakeCase,
} from './CodegenProfile';

function pageForStep(step: TraceStep, plan: GenerationPlan): PlannedFile | undefined {
  return plan.pageObjects.find((page) => {
    if (!step.url || !page.urlPattern) return false;
    try {
      return new RegExp(page.urlPattern).test(step.url);
    } catch {
      return step.url.includes(page.urlPattern);
    }
  });
}

function pythonLocator(step: TraceStep, receiver = 'self.page'): string | null {
  const selector = step.selector;
  if (!selector) return null;
  const role = roleParts(selector);
  if (role) {
    return role.name
      ? `${receiver}.get_by_role("${escapeDouble(role.role)}", name="${escapeDouble(role.name)}")`
      : `${receiver}.get_by_role("${escapeDouble(role.role)}")`;
  }
  switch (selector.kind) {
    case 'label':
      return `${receiver}.get_by_label("${escapeDouble(selector.value)}")`;
    case 'placeholder':
      return `${receiver}.get_by_placeholder("${escapeDouble(selector.value)}")`;
    case 'testid':
      return `${receiver}.get_by_test_id("${escapeDouble(selector.value)}")`;
    case 'text':
      return `${receiver}.get_by_text("${escapeDouble(selector.value)}")`;
    default:
      return `${receiver}.locator("${escapeDouble(selector.value)}")`;
  }
}

function methodName(step: TraceStep): string {
  if (step.action === 'navigate') return 'goto';
  const base = snakeCase(step.intent || `${step.action}_${step.index}`);
  if (step.action === 'click' && !base.startsWith('click_')) return `click_${base}`;
  if (step.action === 'fill' && !base.startsWith('fill_')) return `fill_${base}`;
  if (step.action === 'assert' && !base.startsWith('assert_')) return `assert_${base}`;
  return base || `${step.action}_${step.index}`;
}

function stepLines(step: TraceStep, receiver = 'page'): string[] {
  const locator = pythonLocator(step, receiver);
  const metadata = step.selector
    ? [`# selector: confidence ${step.selector.confidence.toFixed(2)}`]
    : [];
  const assertionLines = (step.assertions || []).flatMap((assertion) =>
    AssertionEmitter.pythonPlaywright(assertion, receiver)
  );
  switch (step.action) {
    case 'navigate':
      return step.url ? [`${receiver}.goto("${escapeDouble(step.url)}")`, ...assertionLines] : assertionLines;
    case 'click':
      return locator ? [...metadata, `${locator}.click()`, ...assertionLines] : [`# click: ${step.intent}`, ...assertionLines];
    case 'fill':
      return locator ? [...metadata, `${locator}.fill("${escapeDouble(step.value || '')}")`, ...assertionLines] : [`# fill: ${step.intent}`, ...assertionLines];
    case 'select':
      return locator
        ? [...metadata, `${locator}.select_option("${escapeDouble(step.value || '')}")`, ...assertionLines]
        : [`# select: ${step.intent}`, ...assertionLines];
    case 'assert':
      return assertionLines.length > 0 ? assertionLines : locator ? [...metadata, `expect(${locator}).to_be_visible()`] : [`# assert: ${step.intent}`];
    case 'wait':
      return [`${receiver}.wait_for_load_state("networkidle")`];
    default:
      return [`# ${step.action}: ${step.intent}`];
  }
}

function pageObjectContent(page: PlannedFile, steps: TraceStep[], trace: ExecutionTrace): string {
  const methods: string[] = [];
  const seen = new Set<string>();
  for (const step of steps) {
    const name = methodName(step);
    if (seen.has(name)) continue;
    seen.add(name);
    const lines = stepLines(step, 'self.page').map((line) => `        ${line}`);
    if (lines.length === 0) continue;
    methods.push(`    def ${name}(self):\n${lines.join('\n')}`);
  }
  const className = page.className || 'GeneratedPage';
  const url = page.urlPattern || firstUrl(trace) || '';
  return `import re\nfrom playwright.sync_api import Page, expect\n\nfrom tests.generated.pages.base_page import BasePage\n\n\nclass ${className}(BasePage):\n    \"\"\"Generated by WebPilot.\n\n    url_pattern: ${url}\n    \"\"\"\n\n    def __init__(self, page: Page):\n        super().__init__(page)\n\n${methods.join('\n\n') || '    pass'}\n`;
}

export class PythonPlaywrightProfile implements CodegenProfile {
  public readonly id = 'python-playwright-pom';
  public readonly language = 'python';
  public readonly automationTool = 'playwright';
  public readonly testFramework = 'pytest';
  public readonly patterns = ['pom', 'simple'];

  public matches(profile: CodegenProfilePlan): boolean {
    return profile.language === 'python' && profile.automationTool === 'playwright';
  }

  public specPath(slug: string, _profile: CodegenProfilePlan): string {
    return `tests/generated/test_${snakeCase(slug)}.py`;
  }

  public pagePath(className: string, _profile: CodegenProfilePlan, _url?: string): string {
    return `tests/generated/pages/${snakeCase(className)}.py`;
  }

  public replayCommand(specPath: string): string {
    return `pytest ${specPath}`;
  }

  public emit(trace: ExecutionTrace, plan: GenerationPlan): GeneratedFile[] {
    const usePom = plan.profile.frameworkPattern !== 'simple';
    const files: GeneratedFile[] = [];
    const pageMethodByStep = new Map<number, { variable: string; method: string }>();

    if (usePom) {
      for (const page of plan.pageObjects) {
        const steps = trace.steps.filter((step) => pageForStep(step, { ...plan, pageObjects: [page] }));
        if (steps.length === 0) continue;
        files.push({ path: page.path, content: pageObjectContent(page, steps, trace) });
        for (const step of steps) {
          pageMethodByStep.set(step.index, {
            variable: camelCase(page.className || 'generatedPage'),
            method: methodName(step),
          });
        }
      }
    }

    const imports = ['import re', 'from playwright.sync_api import Page, expect'];
    if (usePom) {
      for (const page of plan.pageObjects) {
        if (!page.className) continue;
        const modulePath = page.path
          .replace(/^tests\/generated\//, '')
          .replace(/^tests\//, '')
          .replace(/\.py$/, '')
          .replace(/\//g, '.');
        imports.push(`from ${modulePath} import ${page.className}`);
      }
    }

    const lines: string[] = [...imports, '', '', `def test_${snakeCase(trace.scenarioSlug)}(page: Page):`];
    const instantiated = new Set<string>();
    for (const step of trace.steps) {
      const mapped = pageMethodByStep.get(step.index);
      if (usePom && mapped) {
        if (!instantiated.has(mapped.variable)) {
          const page = pageForStep(step, plan);
          if (page?.className) {
            lines.push(`    ${mapped.variable} = ${page.className}(page)`);
            instantiated.add(mapped.variable);
          }
        }
        lines.push(`    ${mapped.variable}.${mapped.method}()`);
        continue;
      }
      for (const line of stepLines(step, 'page')) {
        lines.push(`    ${line}`);
      }
    }
    lines.push('');
    files.push({ path: plan.specPath, content: lines.join('\n') });
    return files;
  }

  public validationCommand(_profile: CodegenProfilePlan): string {
    return 'python -m compileall -q tests/generated tests/support';
  }
}
