import { GeneratedFile } from '../../../agents/CodegenAgent';
import { ExecutionTrace, TraceStep } from '../ExecutionTrace';
import { CodegenProfilePlan, GenerationPlan, PlannedFile } from '../GenerationPlan';
import { AssertionEmitter } from '../../assertions/AssertionEmitter';
import {
  camelCase,
  CodegenProfile,
  escapeSingle,
  firstUrl,
  roleParts,
  snakeCase,
} from './CodegenProfile';

function pageForStep(step: TraceStep, plan: GenerationPlan): PlannedFile | undefined {
  return plan.pageObjects.find((page) => {
    if (!step.url || !page.urlPattern) return false;
    try {
      return new RegExp(page.urlPattern).test(step.url);
    } catch {
      return step.url.includes(page.urlPattern);
    }
  });
}

function wdioSelector(step: TraceStep): string | null {
  const selector = step.selector;
  if (!selector) return null;
  const role = roleParts(selector);
  if (role?.name) {
    return `$('[role="${escapeSingle(role.role)}"]*=${escapeSingle(role.name)}')`;
  }
  switch (selector.kind) {
    case 'label':
      return `$('label=${escapeSingle(selector.value)}')`;
    case 'placeholder':
      return `$('[placeholder="${escapeSingle(selector.value)}"]')`;
    case 'testid':
      return `$('[data-testid="${escapeSingle(selector.value)}"]')`;
    case 'text':
      return `$('*=${escapeSingle(selector.value)}')`;
    case 'xpath':
      return `$('${escapeSingle(selector.value)}')`;
    default:
      return `$('${escapeSingle(selector.value)}')`;
  }
}

function methodName(step: TraceStep): string {
  if (step.action === 'navigate') return 'goTo';
  const base = snakeCase(step.intent || `${step.action}_${step.index}`);
  if (step.action === 'click' && !base.startsWith('click_')) return `click_${base}`;
  if (step.action === 'fill' && !base.startsWith('fill_')) return `fill_${base}`;
  if (step.action === 'assert' && !base.startsWith('assert_')) return `assert_${base}`;
  return base || `${step.action}_${step.index}`;
}

function stepLines(step: TraceStep): string[] {
  const locator = wdioSelector(step);
  const metadata = step.selector
    ? [`// selector: confidence ${step.selector.confidence.toFixed(2)}`]
    : [];
  const assertionLines = (step.assertions || []).flatMap((assertion) =>
    AssertionEmitter.webdriverIO(assertion)
  );
  switch (step.action) {
    case 'navigate':
      return step.url ? [`await browser.url('${escapeSingle(step.url)}');`, ...assertionLines] : assertionLines;
    case 'click':
      return locator
        ? [...metadata, `await ${locator}.click();`, ...assertionLines]
        : [`// click: ${step.intent}`, ...assertionLines];
    case 'fill':
      return locator
        ? [...metadata, `await ${locator}.setValue('${escapeSingle(step.value || '')}');`, ...assertionLines]
        : [`// fill: ${step.intent}`, ...assertionLines];
    case 'select':
      return locator
        ? [...metadata, `await ${locator}.selectByVisibleText('${escapeSingle(step.value || '')}');`, ...assertionLines]
        : [`// select: ${step.intent}`, ...assertionLines];
    case 'assert':
      return assertionLines.length > 0
        ? assertionLines
        : locator
          ? [...metadata, `await ${locator}.waitForDisplayed();`]
          : [`// assert: ${step.intent}`];
    case 'wait':
      return [`await browser.pause(1000);`];
    default:
      return [`// ${step.action}: ${step.intent}`];
  }
}

function pageObjectContent(page: PlannedFile, steps: TraceStep[], trace: ExecutionTrace): string {
  const className = page.className || 'GeneratedPage';
  const methods = steps
    .map((step) => {
      const lines = stepLines(step).map((line) => `    ${line}`);
      return `  async ${methodName(step)}() {\n${lines.join('\n')}\n  }`;
    })
    .join('\n\n');
  return `import { browser } from '@wdio/globals';
import { BasePage } from '../BasePage';

/** Generated by WebPilot. urlPattern: ${page.urlPattern || firstUrl(trace) || ''} */
export class ${className} extends BasePage {
${methods || '  // No generated actions yet.'}
}
`;
}

export class TypeScriptWebdriverIOProfile implements CodegenProfile {
  public readonly id = 'typescript-webdriverio-pom';
  public readonly language = 'typescript';
  public readonly automationTool = 'webdriverio';
  public readonly testFramework = 'webdriverio';
  public readonly patterns = ['simple', 'pom'];

  public matches(profile: CodegenProfilePlan): boolean {
    return profile.language === 'typescript' && profile.automationTool === 'webdriverio';
  }

  public specPath(slug: string, _profile: CodegenProfilePlan): string {
    return `test/specs/generated/${snakeCase(slug)}.spec.ts`;
  }

  public pagePath(className: string, _profile: CodegenProfilePlan, _url?: string): string {
    return `test/pageobjects/${className}.ts`;
  }

  public replayCommand(specPath: string): string {
    return `npx wdio run wdio.conf.ts --spec ${specPath}`;
  }

  public emit(trace: ExecutionTrace, plan: GenerationPlan): GeneratedFile[] {
    const usePom = plan.profile.frameworkPattern !== 'simple';
    const files: GeneratedFile[] = [];
    const pageMethodByStep = new Map<number, { variable: string; method: string; className: string }>();

    if (usePom) {
      for (const page of plan.pageObjects) {
        const steps = trace.steps.filter((step) => pageForStep(step, { ...plan, pageObjects: [page] }));
        if (steps.length === 0) continue;
        files.push({ path: page.path, content: pageObjectContent(page, steps, trace) });
        for (const step of steps) {
          if (!page.className) continue;
          pageMethodByStep.set(step.index, {
            className: page.className,
            variable: camelCase(page.className),
            method: methodName(step),
          });
        }
      }
    }

    const imports = ["import { browser, expect } from '@wdio/globals';"];
    if (usePom) {
      for (const page of plan.pageObjects) {
        if (page.className) {
          imports.push(`import { ${page.className} } from '../pageobjects/${page.className}';`);
        }
      }
    }

    const body: string[] = [];
    const instantiated = new Set<string>();
    for (const step of trace.steps) {
      const mapped = pageMethodByStep.get(step.index);
      if (usePom && mapped) {
        if (!instantiated.has(mapped.variable)) {
          body.push(`    const ${mapped.variable} = new ${mapped.className}();`);
          instantiated.add(mapped.variable);
        }
        body.push(`    await ${mapped.variable}.${mapped.method}();`);
        continue;
      }
      for (const line of stepLines(step)) {
        body.push(`    ${line}`);
      }
    }

    const content = `${imports.join('\n')}

describe('${trace.scenario.replace(/'/g, "\\'")}', () => {
  it('replays the WebPilot flow', async () => {
${body.join('\n')}
  });
});
`;
    files.push({ path: plan.specPath, content });
    return files;
  }

  public validationCommand(_profile: CodegenProfilePlan): string {
    return 'npx tsc --noEmit';
  }
}
